# Use an official MariaDB runtime as a parent image
FROM mariadb:10.5

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=WhatsABook
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=root

# Expose port 3306
EXPOSE 3306